### ISSUE TITLE
BioC 2022 logo

### ISSUE THREAD

**Issue by mdozmorov** [Bioconductor/BioC2022#17]
It looks like we don't have the hex sticker for the [BioC2022](https://bioc2022.bioconductor.org/) conference. @jorainer, can you, please, help? Since it is planned in Seattle/virtual, maybe, reuse [the awesome drafts for the BioC2021 conference](https://github.com/Bioconductor/BiocStickers/tree/master/events/Bioc2021)?

**Comment by jorainer** [comment]
Actually, we agreed that Marcel will work on that (see [this issue](https://github.com/Bioconductor/BiocStickers/issues/169)).

**Comment by mdozmorov** [comment]
Ah, didn't know. Marcel, can you look at it? @LiNk-NY

**Comment by LiNk-NY** [comment]
Hi Mikhail, @mdozmorov 

I have been working on it. I will finalize it soon. 
What is the timeline for the sticker? 

Best,
Marcel

**Comment by mdozmorov** [comment]
Thanks, Marcel. Registration will open soon, maybe, in a couple of weeks. It'll be good to have a logo by then.

**Comment by mdozmorov** [comment]
The sticker is at https://github.com/Bioconductor/BiocStickers/issues/169
