### ISSUE TITLE
Modular schedule

### ISSUE THREAD

**Issue by mdozmorov** [Bioconductor/BioC2022#20]
Previously, schedule was hard-coded in Markdown, like https://bioc2021.bioconductor.org/schedule/. Can we make the schedule page auto-populating from a YAML file? 

Each record should contain date, time, session type, presenting author, social media handle, presentation title, GitHub link or abstract, Youtube link. Titles may be linked to GitHub/abstracts, or, if possible, abstracts may pop up when hovering over title. Entries may be colored by session type. Parallel sessions may be listed one after another.

[Current schedule](https://docs.google.com/spreadsheets/d/1ShvNhDTk1nDP_pLNz1JJZaTn618h54NQMl2K3o7hveU/edit#gid=0). @sdgamboa , can you help?

**Comment by sdgamboa** [comment]
@mdozmorov, sure, I'll look into it.

**Comment by sdgamboa** [comment]
I think we can close this issue now.

**Comment by mdozmorov** [comment]
Thanks, @sdgamboa , @Krithika-Bhuvan - the schedule looks great!
