### ISSUE TITLE
create a template repository for other regional conferences

### ISSUE THREAD

**Issue by LiNk-NY** [Bioconductor/BioC2022#43]
It'd be good to have a template repository similar to https://github.com/seandavi/BuildABiocWorkshop for other conferences to use.

**Comment by mdozmorov** [comment]
Good point. A basic template [exists](https://github.com/mdozmorov/conference_template), but @sdgamboa made so many improvements it is now obsolete. Samuel, can you help to create a new barebone template?

**Comment by sdgamboa** [comment]
Happy to help! Changes would go to the [same repo](https://github.com/mdozmorov/conference_template) as above?

**Comment by mdozmorov** [comment]
It'll be best to create https://github.com/Bioconductor/conference_template. I believe, @lshep can create it and add you as admin. Lori, can you help?

Another enhancement is the registration form built into the website. Mike Smith @grimbough did it for the EuroBioC2022 conference in [these pull requests](https://github.com/Bioconductor/EuroBioC2022/pulls?q=is%3Apr+is%3Aclosed). It is currently paused but it worked well. If we can add it to the template, that'll be great.

**Comment by LiNk-NY** [comment]
I've created a repo here: https://github.com/Bioconductor/BioC_template
I will add you shortly.
cc: @lshep
