### ISSUE TITLE
Short talk videos not showing

### ISSUE THREAD

**Issue by mdozmorov** [Bioconductor/BioC2022#54]
Short talk tracks contain several talks, e.g., [RNA Track](https://bioc2022.bioconductor.org/abstracts/track6/). Many now have Youtube videos, added to their yaml files, e.g., [day2_0900_Shorttalk_paper15.yaml](https://github.com/Bioconductor/BioC2022/blob/master/data/abstracts/day2_0900_Shorttalk_paper15.yaml). But for them, the Youtube links never show up. Can they be shown on the schedule? And/or individual abstracts? @sdgamboa, can you look into it?

**Comment by sdgamboa** [comment]
@mdozmorov, I'll look into it.

**Comment by mdozmorov** [comment]
Pinging this issue - we got several short talk videos, they are added to YAML files. I'm not sure how to make them show on the schedule page.

**Comment by sdgamboa** [comment]
Hi, @mdozmorov. I added the YT links to the tracks in the schedule (day3 only). The YT links are also displayed on the individual abstract pages. #55 

Note that individual short talks are not actually displayed on the schedule, but the short talk tracks are. So the youtube link needs to be added to the individual short talk yaml file and to the short talks track yaml (fields youtube-youtube4). Maybe there is a more efficient way to do this (to avoid repetition), I'll do some research on how to achieve that later.

So day3 short talks are complete, would you add the other links to the remaining tracks?
